docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.23.2-0
  working_directory: ~/app

version: 2
jobs:
  run-unit-tests:
    <<: *docker-defaults
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Run unit tests
        command: |
          docker-compose run test

workflows:
  version: 2
  test:
    jobs:
    - run-unit-tests